#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap "rm -f .git/tags.$$" EXIT
git ls-files | \
	exctags --tag-relative=yes -L - -f"$dir/$$.tags"
mv .git/$$.tags .git/tags
